# Generated by Django 3.2.7 on 2021-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
