# Generated by Django 3.2.7 on 2021-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_alter_pessoacolaborador_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='demissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
