# Generated by Django 3.2.7 on 2021-09-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20210929_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('validade', models.DateField()),
                ('valor', models.CharField(max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='contratos/%Y/%m')),
                ('datahora_ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
