# Generated by Django 3.2.7 on 2021-09-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='data',
            new_name='inicio_validade',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='validade',
            new_name='termino_validade',
        ),
    ]
