# Generated by Django 3.2.7 on 2021-09-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20210930_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='inicio_validade',
            new_name='inicio_vigencia',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='termino_validade',
            new_name='termino_vigencia',
        ),
    ]
