# Generated by Django 3.2.7 on 2021-09-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_auto_20210930_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='is_active',
        ),
    ]
