# Generated by Django 3.2.7 on 2021-10-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0007_remove_contrato_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, upload_to='escolas/logos/%Y'),
        ),
        migrations.AddField(
            model_name='pessoacolaborador',
            name='contratos',
            field=models.ManyToManyField(related_name='colaborador', to='administrativo.Contrato'),
        ),
        migrations.AddField(
            model_name='pessoaestudante',
            name='contratos',
            field=models.ManyToManyField(related_name='estudante', to='administrativo.Contrato'),
        ),
        migrations.AddField(
            model_name='pessoaresponsavel',
            name='contratos',
            field=models.ManyToManyField(related_name='responsavel', to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='estudantes',
            field=models.ManyToManyField(related_name='responsaveis', to='administrativo.PessoaEstudante'),
        ),
    ]
