# Generated by Django 3.2.7 on 2021-10-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_auto_20210930_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='imagem',
        ),
        migrations.AddField(
            model_name='contrato',
            name='arquivo',
            field=models.FileField(default=None, upload_to='contratos/arquivo/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='digitalizacao',
            field=models.ImageField(blank=True, upload_to='contratos/digitalizacao/%Y/%m'),
        ),
    ]
