# Generated by Django 3.2.7 on 2021-10-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_contrato_data_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='escola',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola'),
            preserve_default=False,
        ),
    ]
