# Generated by Django 3.2.7 on 2021-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0011_contrato_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='contratos',
            field=models.ManyToManyField(blank=True, related_name='colaborador', to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='contratos',
            field=models.ManyToManyField(blank=True, related_name='estudante', to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='contratos',
            field=models.ManyToManyField(blank=True, related_name='responsavel', to='administrativo.Contrato'),
        ),
    ]
