# Generated by Django 3.2.7 on 2021-10-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0012_auto_20211003_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
