# Generated by Django 3.2.7 on 2021-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0013_auto_20211003_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='digitalizacao',
            field=models.ImageField(blank=True, null=True, upload_to='contratos/digitalizacao/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='celular',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='escola',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='escolas/logos/%Y'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='contratos',
            field=models.ManyToManyField(blank=True, null=True, related_name='colaborador', to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas/fotos/colaboradores/%Y'),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='ramal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='contratos',
            field=models.ManyToManyField(blank=True, null=True, related_name='estudante', to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas/fotos/estudantes/%Y'),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='contratos',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsavel', to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas/fotos/responsaveis/%Y'),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
