# Generated by Django 3.2.7 on 2021-10-09 23:36

import athena.custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_auto_20211007_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=athena.custom_storages.MediaStorage(), upload_to='escolas/logos/%Y'),
        ),
    ]
