# Generated by Django 3.2.7 on 2021-10-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0017_auto_20211009_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulosEscola',
            fields=[
                ('descricao', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dashboard', models.BooleanField()),
                ('administrativo_escolas', models.BooleanField()),
                ('administrativo_pessoas_estudantes', models.BooleanField()),
                ('administrativo_pessoas_responsaveis', models.BooleanField()),
                ('administrativo_pessoas_colaboradores', models.BooleanField()),
                ('administrativo_contratos', models.BooleanField()),
                ('administrativo_secretaria', models.BooleanField()),
                ('administrativo_recepcao', models.BooleanField()),
                ('administrativo_relatorios', models.BooleanField()),
                ('pedagogico_cursos', models.BooleanField()),
                ('pedagogico_turmas', models.BooleanField()),
                ('pedagogico_boletim', models.BooleanField()),
                ('pedagogico_diario_classe', models.BooleanField()),
                ('pedagogico_sala_virtual', models.BooleanField()),
                ('pedagogico_vestibulares', models.BooleanField()),
                ('pedagogico_relatorios', models.BooleanField()),
                ('financeiro_bancos', models.BooleanField()),
                ('financeiro_movimentacoes', models.BooleanField()),
                ('financeiro_relatorios', models.BooleanField()),
                ('institucional_cadastro_escolar', models.BooleanField()),
                ('institucional_ano_academico', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola')),
            ],
        ),
    ]
