# Generated by Django 3.2.7 on 2021-10-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0018_modulosescola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulosescola',
            name='descricao',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulosescola',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola', unique=True),
        ),
    ]
