# Generated by Django 3.2.7 on 2021-10-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0019_auto_20211011_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulosescola',
            name='escola',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola'),
        ),
    ]
