# Generated by Django 3.2.7 on 2021-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0024_auto_20211013_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoeducacional',
            name='valor',
        ),
        migrations.AlterField(
            model_name='contratoeducacional',
            name='digitalizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contratotrabalhista',
            name='digitalizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='escola',
            name='celular',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='escola',
            name='complemento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='escola',
            name='logo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='escola',
            name='site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='contratos',
            field=models.ManyToManyField(blank=True, null=True, related_name='colaborador', to='administrativo.ContratoTrabalhista'),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='foto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='ramal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoacolaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='complemento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='contratos',
            field=models.ManyToManyField(blank=True, null=True, related_name='estudante', to='administrativo.ContratoEducacional'),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='foto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='complemento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='contratos',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsavel', to='administrativo.ContratoEducacional'),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='foto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
