# Generated by Django 3.2.7 on 2021-10-17 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0023_auto_20211015_2251'),
        ('administrativo', '0026_auto_20211015_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratoeducacional',
            old_name='arquivo',
            new_name='arquivo_contrato',
        ),
        migrations.RemoveField(
            model_name='pessoaestudante',
            name='contratos',
        ),
        migrations.RemoveField(
            model_name='pessoaresponsavel',
            name='contratos',
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pedagogico.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='data_inicio_pagamento_curso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='data_pagamento_matricula',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='desconto_pagamento_curso',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='desconto_pagamento_matricula',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='dia_pagamento_curso',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='estudante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrativo.pessoaestudante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='parcelas_pagamento_curso',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.pessoaresponsavel'),
        ),
        migrations.AddField(
            model_name='contratoeducacional',
            name='turma',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pedagogico.turma'),
            preserve_default=False,
        ),
    ]
