# Generated by Django 3.2.7 on 2021-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0027_auto_20211017_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoeducacional',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
