# Generated by Django 3.2.7 on 2021-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0028_contratoeducacional_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoeducacional',
            name='estudante_contratante',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
