# Generated by Django 3.2.7 on 2021-10-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0029_contratoeducacional_estudante_contratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoeducacional',
            name='codigo',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
