# Generated by Django 3.2.7 on 2021-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0030_contratoeducacional_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulosescola',
            name='institucional_integracoes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
