# Generated by Django 3.2.7 on 2021-10-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0031_modulosescola_institucional_integracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoeducacional',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pessoaestudante',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pessoaresponsavel',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
