# Generated by Django 3.2.7 on 2021-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0032_auto_20211026_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoeducacional',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='pessoaestudante',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='pessoaresponsavel',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
