# Generated by Django 3.2.7 on 2021-11-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0033_auto_20211027_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='assinatura',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
