# Generated by Django 3.2.7 on 2021-11-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0034_escola_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulosescola',
            name='institucional_plataformas',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
