# Generated by Django 3.2.7 on 2022-01-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0031_plataforma_link'),
        ('administrativo', '0035_modulosescola_institucional_plataformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloContratoEducacional',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('contrato', models.TextField()),
                ('datahora_ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.curso')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.turma')),
            ],
        ),
    ]
