# Generated by Django 3.2.7 on 2022-01-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0036_modelocontratoeducacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocontratoeducacional',
            name='codigo',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='modelocontratoeducacional',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
