# Generated by Django 3.2.7 on 2021-10-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0002_rename_divisao_periodos_curso_periodicidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='divisao_periodos',
        ),
    ]
