# Generated by Django 3.2.7 on 2021-10-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0004_remove_curso_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='codigo',
        ),
    ]
