# Generated by Django 3.2.7 on 2021-10-07 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0005_auto_20211007_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='ementa',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horarios',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario_inicio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario_termino',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='weekday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
