# Generated by Django 3.2.7 on 2021-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0013_auto_20211003_2102'),
        ('pedagogico', '0006_auto_20211007_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='escola',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola'),
            preserve_default=False,
        ),
    ]
