# Generated by Django 3.2.7 on 2021-10-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0007_curso_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='parcelamento_curso',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='parcelamento_material',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_curso',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_material',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
