# Generated by Django 3.2.7 on 2021-10-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0014_auto_20211007_1541'),
        ('pedagogico', '0008_auto_20211007_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.pessoacolaborador'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='parcelamento_curso',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='parcelamento_material',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='proposta_pedagogica',
            field=models.FileField(blank=True, null=True, upload_to='disciplinas/ementas/%Y'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_curso',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_material',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_professores', to='administrativo.pessoacolaborador'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='turma', to='administrativo.PessoaEstudante'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.pessoacolaborador'),
        ),
    ]
