# Generated by Django 3.2.7 on 2021-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_auto_20211007_1544'),
        ('pedagogico', '0009_auto_20211007_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turma', to='administrativo.PessoaEstudante'),
        ),
    ]
