# Generated by Django 3.2.7 on 2021-10-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_auto_20211007_1544'),
        ('pedagogico', '0010_alter_turma_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola'),
            preserve_default=False,
        ),
    ]
