# Generated by Django 3.2.7 on 2021-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0011_turma_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='vagas',
            field=models.CharField(default='0', max_length=4),
            preserve_default=False,
        ),
    ]
