# Generated by Django 3.2.7 on 2021-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0012_auto_20211007_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
