# Generated by Django 3.2.7 on 2021-10-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0013_alter_turma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
