# Generated by Django 3.2.7 on 2021-10-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0014_auto_20211007_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='proposta_pedagogica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
