# Generated by Django 3.2.7 on 2021-10-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0015_alter_curso_proposta_pedagogica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
