# Generated by Django 3.2.7 on 2021-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0016_auto_20211013_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
