# Generated by Django 3.2.7 on 2021-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0022_auto_20211012_2243'),
        ('pedagogico', '0017_auto_20211013_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, null=True, related_name='curso', to='pedagogico.Disciplina'),
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professores',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplina_professores', to='administrativo.PessoaColaborador'),
        ),
    ]
