# Generated by Django 3.2.7 on 2021-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0022_auto_20211012_2243'),
        ('pedagogico', '0019_auto_20211013_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='professores', to='administrativo.PessoaColaborador'),
        ),
    ]
