# Generated by Django 3.2.7 on 2021-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0025_auto_20211015_2250'),
        ('pedagogico', '0021_auto_20211013_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, null=True, related_name='cursos', to='pedagogico.Disciplina'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='parcelamento_curso',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='parcelamento_material',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='proposta_pedagogica',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_curso',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_material',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='turmas', to='administrativo.PessoaEstudante'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_termino',
            field=models.DateField(blank=True),
        ),
    ]
