# Generated by Django 3.2.7 on 2021-10-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0023_auto_20211015_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='data_final_cancelamento',
        ),
    ]
