# Generated by Django 3.2.7 on 2021-10-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0024_remove_curso_data_final_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
