# Generated by Django 3.2.7 on 2021-10-26 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0025_auto_20211023_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='curso',
            name='datahora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='datahora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='datahora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='turmas', to='pedagogico.Disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='parcelamento_curso',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='turma',
            name='parcelamento_material',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='turma',
            name='valor_curso',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='turma',
            name='valor_material',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
