# Generated by Django 3.2.7 on 2021-10-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0027_auto_20211026_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
