# Generated by Django 3.2.7 on 2021-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0028_turma_id_conta_azul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
