# Generated by Django 3.2.7 on 2021-11-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0034_escola_assinatura'),
        ('pedagogico', '0029_alter_turma_id_conta_azul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=7)),
                ('descricao', models.CharField(max_length=100)),
                ('datahora_ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('datahora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola')),
            ],
        ),
    ]
