# Generated by Django 3.2.7 on 2021-11-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0030_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
