"""
Django settings for athena project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os, sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['athena.thrucode.com.br', '127.0.0.1']


# SECURITY WARNING: keep the secret key used in production secret!

if not DEBUG:
    SECRET_KEY = os.environ['SECRET_KEY']
else:
    SECRET_KEY = '8IyEHaGkOvDOMgmk0Ky4PvU8RXqnypBsIFcR0SJxdZnZcAFLcpT6tWJpd2Cd'


# Application definition

INSTALLED_APPS = [
    'debug_permissions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'django_filters',
    'storages',
    'index',
    'administrativo',
    'pedagogico',
    'financeiro',
    'institucional',
    'usuario',
    'funcionalidades',
    'api',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'athena.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'assets/pages')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'athena.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'athena',
            'USER': 'django',
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': 'thrucode.cgffddxe4wvm.us-east-1.rds.amazonaws.com',
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'athena',
            'USER': 'django',
            'PASSWORD': '#w%&QPdcVa%wBsE2hJRW5htlfI4Rqg#v9TqoeRmFQWTqQQ$0Mh',
            'HOST': 'thrucode.cgffddxe4wvm.us-east-1.rds.amazonaws.com',
            'PORT': '5432',
        }
    }


# Authentication

LOGIN_URL = 'login'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#AUTHENTICATION_BACKENDS = [
#    'django.contrib.auth.backends.RemoteUserBackend',
#]

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True


# Email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.zoho.com'

EMAIL_HOST_USER = 'hermes@thrucode.com.br'
DEFAULT_FROM_EMAIL = 'hermes@thrucode.com.br'
EMAIL_HOST_PASSWORD = 'unHsJHd5N3sh'

"""EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'

if not DEBUG:
    EMAIL_HOST_USER = os.environ['EMAIL_USER']
    DEFAULT_FROM_EMAIL = os.environ['EMAIL_USER']
    EMAIL_HOST_PASSWORD = os.environ['EMAIL_PASSWORD']
else:
    EMAIL_HOST_USER = 'AKIA5Q2ODCHCTTILUEMB'
    DEFAULT_FROM_EMAIL = 'athena@hermes.thrucode.com'
    EMAIL_HOST_PASSWORD = 'BOxXV2lKmauZDubG3zaQo0Bj7FGsXJUiJRc1rhtpYgVj'"""

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False


# REST Framework

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Apps folder

PROJECT_ROOT = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(PROJECT_ROOT, '../apps'))


# Messages

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.SUCCESS: 'success',
}


"""# Max Data
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000"""


# DJANGO STORAGES - S3

if not DEBUG:
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_REGION_NAME = os.environ['AWS_S3_REGION_NAME']
else:
    AWS_ACCESS_KEY_ID = 'AKIA5Q2ODCHCQVIGRYNT'
    AWS_SECRET_ACCESS_KEY = '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'
    AWS_STORAGE_BUCKET_NAME = 'thrucodeathenastatic'
    AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

STATIC_LOCATION = 'static'
STATICFILES_STORAGE = 'athena.custom_storages.StaticStorage'
STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, STATIC_LOCATION)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets/collectstatic')
]

MEDIA_LOCATION = 'media'
DEFAULT_FILE_STORAGE = 'athena.custom_storages.MediaStorage'
MEDIA_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, MEDIA_LOCATION)

AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None
