# Generated by Django 3.2.7 on 2021-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoAcademico',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('periodicidade', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GruposUsuarios',
            fields=[
                ('descricao', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dashboard', models.BooleanField()),
                ('administrativo_escolas', models.BooleanField()),
                ('administrativo_pessoas_estudantes', models.BooleanField()),
                ('administrativo_pessoas_responsaveis', models.BooleanField()),
                ('administrativo_pessoas_colaboradores', models.BooleanField()),
                ('administrativo_contratos', models.BooleanField()),
                ('administrativo_secretaria', models.BooleanField()),
                ('administrativo_recepcao', models.BooleanField()),
                ('administrativo_relatorios', models.BooleanField()),
                ('pedagogico_cursos', models.BooleanField()),
                ('pedagogico_disciplinas', models.BooleanField()),
                ('pedagogico_turmas', models.BooleanField()),
                ('pedagogico_boletim', models.BooleanField()),
                ('pedagogico_diario_classe', models.BooleanField()),
                ('pedagogico_sala_virtual', models.BooleanField()),
                ('pedagogico_vestibulares', models.BooleanField()),
                ('pedagogico_relatorios', models.BooleanField()),
                ('financeiro_bancos', models.BooleanField()),
                ('financeiro_movimentacoes', models.BooleanField()),
                ('financeiro_relatorios', models.BooleanField()),
                ('institucional_cadastro_escolar', models.BooleanField()),
                ('institucional_ano_academico', models.BooleanField()),
            ],
        ),
    ]
