# Generated by Django 3.2.7 on 2021-10-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_delete_gruposusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
