# Generated by Django 3.2.7 on 2021-10-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0008_usuariospermissoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_contratos',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_escolas',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_pessoas_colaboradores',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_pessoas_estudantes',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_pessoas_responsaveis',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_recepcao',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_relatorios',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='administrativo_secretaria',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='dashboard',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='financeiro_bancos',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='financeiro_movimentacoes',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='financeiro_relatorios',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='institucional_ano_academico',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='institucional_cadastro_escolar',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='institucional_usuarios_permissoes',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_boletim',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_cursos',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_diario_classe',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_relatorios',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_sala_virtual',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_turmas',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariospermissoes',
            name='pedagogico_vestibulares',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('VER', 'Ver'), ('VER_EDITAR', 'Ver e editar'), ('VER_EDITAR_APAGAR', 'Ver, editar e apagar')], max_length=50),
        ),
    ]
