# Generated by Django 3.2.7 on 2021-10-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0010_auto_20211012_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='codigo',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
