# Generated by Django 3.2.7 on 2021-10-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0031_modulosescola_institucional_integracoes'),
        ('institucional', '0011_auto_20211023_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integracoes',
            fields=[
                ('descricao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('conta_azul', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.escola')),
            ],
        ),
    ]
