# Generated by Django 3.2.7 on 2021-10-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0013_integracaocontaazul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaocontaazul',
            name='is_active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.integracoes'),
        ),
    ]
