# Generated by Django 3.2.7 on 2021-10-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0014_alter_integracaocontaazul_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integracaocontaazul',
            name='is_active',
        ),
    ]
