# Generated by Django 3.2.7 on 2021-10-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0016_integracaocontaazul_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaocontaazul',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='integracaocontaazul',
            name='expires_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integracaocontaazul',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integracaocontaazul',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
