# Generated by Django 3.2.7 on 2021-10-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0017_auto_20211024_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaocontaazul',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
