# Generated by Django 3.2.7 on 2021-10-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0018_integracaocontaazul_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracoes',
            name='conta_azul',
            field=models.BooleanField(default=False),
        ),
    ]
