# Generated by Django 3.2.7 on 2021-10-26 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0019_alter_integracoes_conta_azul'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='datahora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integracaocontaazul',
            name='datahora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integracaocontaazul',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integracoes',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuariospermissoes',
            name='datahora_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariospermissoes',
            name='datahora_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
