# Generated by Django 3.2.7 on 2021-11-06 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0034_escola_assinatura'),
        ('institucional', '0020_auto_20211026_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaocontaazul',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracaocontaazul', to='administrativo.escola'),
        ),
    ]
