# Generated by Django 3.2.7 on 2021-10-04 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PERSONALIZADO', 'Personalizado'), ('NOVO_USUARIO', 'Novo usuário'), ('ESQUECI_MINHA_SENHA', 'Esqueci minha senha')], max_length=50)),
                ('remetente_nome', models.CharField(max_length=50)),
                ('remetente_email', models.EmailField(blank=True, max_length=254)),
                ('destinatarios', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem_txt', models.TextField(blank=True)),
                ('mensagem_html', models.CharField(blank=True, max_length=50)),
                ('variaveis', models.JSONField(blank=True)),
            ],
        ),
    ]
