# Generated by Django 3.2.7 on 2021-10-04 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0002_auto_20211004_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='ccs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='email',
            name='mensagem_html',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
