# Generated by Django 3.2.7 on 2021-10-05 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0004_alter_email_variaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='ccs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='email',
            name='variaveis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
