# Generated by Django 3.2.7 on 2021-10-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0005_auto_20211005_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='emails/anexos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='email',
            name='mensagem_html',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='mensagem_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='remetente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='variaveis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
