# Generated by Django 3.2.7 on 2021-10-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0006_auto_20211007_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='anexos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
