# Generated by Django 3.2.7 on 2021-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidades', '0007_alter_email_anexos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='anexos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='mensagem_html',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='mensagem_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='remetente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='variaveis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
